import './index.css'
import { render, createElement, createTextElement, VirtualDomElement } from 'xnova';

// Function to create the header with a logo and navigation
const createHeader = (): VirtualDomElement => {
  return createElement('header', {
    class: 'flex justify-between items-center p-4 bg-gray-900 text-white'
  }, {},
    createElement('div', {
      class: 'text-lg font-bold'
    }, {}, createTextElement('Xnova')),
    createElement('nav', {}, {},
      createElement('ul', {
        class: 'flex space-x-4'
      }, {},
        createElement('li', {}, {}, createTextElement('Home')),
      )
    )
  );
};

// Function to create the main section with the welcome message and illustration
const createMainSection = (): VirtualDomElement => {
  return createElement('main', {
    class: 'text-center p-10 bg-gradient-to-r from-indigo-500 from-10% via-sky-500 via-30% to-emerald-500 to-90% h-full'
  }, {},
    createElement('h1', {
      class: 'text-5xl font-bold text-white my-4'
    }, {}, createTextElement('Welcome to Xnova')),
    createElement('p', {
      class: 'text-xl text-gray-300 my-4'
    }, {}, createTextElement('Xnova - New JS library')),
    // Textual explanation of the library as a virtual DOM element
    createElement('p', {
      class: 'text-lg text-gray-200 mt-6'
    }, {}, createTextElement('This text is generated by the xnova virtual DOM library, ' +
                             'which enables the creation of user interfaces in a declarative way using JavaScript functions. ' +
                             'Each UI component is a function that returns a virtual DOM element, ' +
                             'representing the structure and content of the component without relying on HTML markup. ' +
                             'The virtual DOM approach is efficient, as it only updates parts of the DOM that have changed.')),
    createElement('div', {
      class: 'mx-auto'
    }, {}, createTextElement('🌐')), // Placeholder for an actual illustration or icon
    createElement('button', {
      class: 'mt-8 bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full',
      onclick: () => {
        alert('Explore the ecosystem!');
      }
    }, {}, createTextElement('Explore Now'))
  );
};

// Function to create the footer with social media links
const createFooter = (): VirtualDomElement => {
  return createElement('footer', {
    class: 'flex justify-center items-center p-4 bg-gray-800 text-white'
  }, {},
    createElement('div', {
      class: 'flex space-x-4'
    }, {},
      createElement('a', { href: 'https://github.com/minamorl/xnova', class: 'hover:text-gray-300' }, {}, createTextElement('GitHub')),
      // Add more social links as needed
    )
  );
};

// Root component that renders the web3 welcome page
export const Web3WelcomePage = (): VirtualDomElement => {
  return createElement('div', {
    class: 'flex flex-col h-screen'
  }, {},
    createHeader(),
    createMainSection(),
    createFooter()
  );
};


// Example of how to use the renderWeb3WelcomePage function
document.addEventListener('DOMContentLoaded', () => {
  const rootElement = document.getElementById('root');
  if (rootElement) {
    const web3WelcomePageElement = Web3WelcomePage();
    // Use the render function from the library
    render(web3WelcomePageElement, rootElement);
    }
});
